### ISSUE TITLE
[Feat] 프로젝트 초기 설정

### ISSUE THREAD

**Issue by kimminkyeu** [Kernel360/E2E2-LOOK-US#1]
## 기능
프로젝트 구현을 위한 초기 설정 입니다.

MySQL 도커 컨테이너 기본 설정과, 데이터가 저장될 경로만 설정했습니다.
추후 협의해서 변경 예정입니다.

- ReadMe.md 에 적힌 Intellij Fomatter를 적용해주세요.

### 브랜치 규칙
- 최소 1명의 코드 리뷰 및 Approve가 필요합니다.

## TODO
- [x] : webhook 설정
- [x] : PR 템플릿, 브랜치 이름 규칙, 머지 리뷰 규칙 설정
- [x] : Docker 설정
- [x] : schema.sql 설정
- [x] : 프론트 Next.js로 할지 말지 등 협의 필요

**Comment by tigris24** [comment]
#6 
docker 세팅, 연결 테스트 완료 했습니다.
