### ISSUE TITLE
[feat] (FE) 회원가입, 마이페이지, 무한스크롤 구현, 팔로우 연동 

### ISSUE THREAD

**Issue by Minju-Kimm** [Kernel360/E2E2-LOOK-US#100]
## 기능
- 회원가입 페이지 구현
- 마이페이지 구현
- 무한 스크롤 구현
- 팔로우 (FE) -> 본인 글이면 팔로우하기 버튼이 안 나타나게 해야합니다.

## Todo

- [ ] 회원가입 페이지 구현 
- [ ] 회원가입 페이지 API 연동 
- [x] 무한 스크롤 구현
- [x] 마이페이지 구현
- [ ] 마이페이지 API 연동
- [ ] 팔로우하기 버튼 구현
