### ISSUE TITLE
[feat] 로그인/회원가입, 프로필 화면, Pwa 세팅

### ISSUE THREAD

**Issue by Minju-Kimm** [Kernel360/E2E2-LOOK-US#134]
## 기능
- 로그인 화면 서비스 취지에 맞게 간단히 바꾸기
- 회원가입 리다이렉트 (gender==NULL 인 경우)
- pwa 적용 전 반응형, 사이즈 맞추기

## Todo
- [ ] 로그인 화면 -> 로고, 구글로 시작하기만
- [ ] 피드에서 바로 회원가입으로 리다이렉트
- [ ] build된 파일 오류 해결

------------이후 추가 예정입니다------------
