### ISSUE TITLE
.env 파일 도입 - application.yaml git에 추가

### ISSUE THREAD

**Issue by kimminkyeu** [Kernel360/E2E2-LOOK-US#84]
### application.yaml 세팅을 팀원 모두 동일하게 하기 위해 Git에 추가합니다.
예민한 데이터는 .env로 따로 관리하도록 변경해야 합니다.
### TODO

- [ ] .env 파일 생성 및 intellij 연결
- [ ] 최대 이미지 request 크기는 1MB를 넘기면 요청을 거절하도록 application.yaml에 명시
- [ ]  로그인 이후 url에 토큰 저장되는것 제거
- [ ]  해더 말고 쿠기로 jwt 검증하도록 설득(with 건우님)
